import{createSign}from'crypto';
const U='https://splendid-ray-99496.upstash.io';
const T='gQAAAAAAAYSoAAIgcDI0Mjk3MjcwYTJiYWQ0ZDExYTE3YTMzMzc1MzBhMTZmNw';
const P='frota-moreno';
const CE='firebase-adminsdk-fbsvc@frota-moreno.iam.gserviceaccount.com';
const TU='https://oauth2.googleapis.com/token';
const PK=['-----BEGIN PRIVATE KEY-----','MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDNHGESlKANspub','M9h75B7rjJCASzyVCIsHdiBlNjkK56bLXUUKjHab18hQ56dxzgX4TSTAayESIjGX','4Q1GjExTWPyKS6Gg3+x6QkRsrvP7/4RtM4ssSg1rZeOIj/dmuFuC0CmU+If3+GhR','bMK+a+um65p+6/XULbDfFTaFQfkigdGuAvL11Yy6XXOq11xHXcpxgTk8nCEYAgLQ','sy23FKlrMftjA/blFS/wTe0/s/svag9J0FeKfU8Sy0YqaMQqSSX0hUONdpSiHVDx','AGWGdh6AhUeuYns2gV0Rp89wkF7tTOQyyQQDoESGFzsuC5eTr3R1VNmQLll0IlY+','LiyW/DAlAgMBAAECggEAKRVhID6i3HuFDY5R82bbBqVOIFRxmwxuBJ2VmZBF1rhV','wXA6LwW5kDeliQcNlA8HRRf2n5AVvLMaqehLJ3FcrGkrlGvXwQh5LnftirN0bWpd','1R2457MhgvySmbz0eh+9PLODULKDUZjxFDYrv8aQGgwhEwEiaVCJl/WAySpQw6dP','AN/Ry+tYDwY7ChVjRtxXgI1hIYoJAOAzr3b4MWfaCXpasXAlMrsJh96AZbqeEt44','Iyynwd6d6xgnQn8lkG+Pqgc+M+75vmFWhSt4AAInzl8AfsvA0rna4qxZYGW92nig','epeVfckWY2Q13cOI4JtG8YjI5a6apPwqt45qC/u1NQKBgQD5LFMYaAsMXW+/uQjm','DZ2573yyuYbY4nkfdzLJx/umj7iuOGN0i6xQOnjnUiHfT2TWDIwpMeFuEmozW8Ch','y/9hs0inZold7rlOoByhJFVHRKuZa6fvD637rgCixurpLqt8iMcwQ523770+3cVN','Ll1Mm8zXto3j348Af94JkSZr0wKBgQDSuwGSmOx+U9/CBMr7xN0sb78u6V3lai+A','HIuwRrLpIMaLcJVDhFQZb/ngV/PlC8vUaEqUNpcp4qM3dTuvAP04W2P1x2JFDBBP','LqAStnN0NoK0kE1OTVkXn4nXwb+MZs33rjfibXyRiAuGXgP41ie/f9QOSHwVA/ky','1zHbt2xRJwKBgQCxwYYyFh8zngCXlIgdnj8UIx4hXist1Dq2UNHBk1IaW9NTLlT9','EptFzMDtvPD/HuN/tAnVZYk9fhOXOfBtPFuetkixa3u5sBEwXxaten7/zaRhWaS+','7b+fmV1IwoFZAntB5026R7JfQr8N9yXGzrmuakMy7D/C/XxFzfJ3fr4bEwKBgFvT','nZXSCYvq5KBZElKvsGlCsJ6ylnX31YcP6VcBF8k6vQnaH1DygusqvkoiSWdPwpxm','bck0GJ7p4ZGzBjT2S2GZgW+CWLIZ1amLebltw9WqQz6HewhZ8C65GInqJZv62FnL','kxKZ/yQzkkIVCcoPF/b8rt0ifN9zgc3DtDg4L30VAoGBALl7vAQfEeOOkQe/ciJa','qxrGB8DV6l/cNoZLh/w/A0o3kl7EcLZ8j+RHZLKF3PoSYUeWDAcjea8TGHsIyQ6c','4PySBSkAGMlo9Od4IWBEIBhBDCuePaKmehDvYtTLjzWzYKWDVcjDafnIIk5gqrZV','3kz9S62OYbZrgWvm7nxlt5U6','-----END PRIVATE KEY-----'].join('\n');
function b(s){return Buffer.from(s).toString('base64').replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
async function gt(){const n=Math.floor(Date.now()/1000);const h=b(JSON.stringify({alg:'RS256',typ:'JWT'}));const p=b(JSON.stringify({iss:CE,sub:CE,aud:TU,iat:n,exp:n+3600,scope:'https://www.googleapis.com/auth/firebase.messaging'}));const s=createSign('RSA-SHA256');s.update(h+'.'+p);const sig=s.sign(PK,'base64').replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const r=await fetch(TU,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion='+h+'.'+p+'.'+sig});return(await r.json()).access_token;}
async function kg(k){try{const r=await fetch(U+'/get/'+encodeURIComponent(k),{headers:{Authorization:'Bearer '+T}});const j=await r.json();return j.result?JSON.parse(j.result):null;}catch(e){return null;}}
export default async function handler(req,res){
const tk=[];
try{const r=await fetch(U+'/keys/fcm_token_*',{headers:{Authorization:'Bearer '+T}});const j=await r.json();if(j.result&&j.result.length)for(const k of j.result){const t=await kg(k);if(t)tk.push(t);}}catch(e){}
if(!tk.length)return res.json({ok:false,msg:'Sem token. Abra o site e toque no sino!'});
const at=await gt();let ok=0;
for(const token of tk){try{const r=await fetch('https://fcm.googleapis.com/v1/projects/'+P+'/messages:send',{method:'POST',headers:{Authorization:'Bearer '+at,'Content-Type':'application/json'},body:JSON.stringify({message:{token,notification:{title:'🚨 Grupo Moreno — Alerta de Meta',body:'Proprietario abaixo da meta! Verifique o dashboard.'},android:{priority:'high'},webpush:{headers:{Urgency:'high'}}}})});if(r.ok)ok++;else console.log(JSON.stringify(await r.json()));}catch(e){console.log(e.message);}}
return res.json({ok:true,tokens:tk.length,enviados:ok,msg:ok>0?'Enviado para '+ok+' celular!':'Falhou'});
}
